title: Francesco Degno
#logo: /assets/img/headshot_circle.png
logo: https://github.githubassets.com/images/icons/emoji/octocat.png
description: Junior Programmer / Game Dev
#show_downloads: true
theme: jekyll-theme-cayman
